# from http://asymmetrical-view.com/2009/05/14/starting-wtih-jekyll.html
destination: ./_site
lsi:         false
port:        4000
highlighter: rouge
markdown:    Kramdown
permalink:   date
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex
  png_url:   /images/latex
  
# from https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/
url: https://www.dantasse.com   # with the https protocol
enforce_ssl: www.dantasse.com   # without any protocol
