# from http://asymmetrical-view.com/2009/05/14/starting-wtih-jekyll.html
destination: ./_site
lsi:         false
port:        4000
highlighter: pygments
markdown:    Kramdown
permalink:   date
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex
  png_url:   /images/latex

